import { launch, sleep } from '../pw.mjs';
const { browser, page, logs } = await launch({ mobile: true, width: 390, height: 844 });
const cdp = await page.context().newCDPSession(page);
await page.goto('http://localhost:4173/?track=rooftop-run');
await page.waitForFunction(() => window.__INKTRACK__?.mode?.race?.state === 'racing', null, { timeout: 60000 });
await page.tap('.tc-small[data-c="pause"]');
await sleep(300);
await page.evaluate(() => window.__INKTRACK__.openEditor({ name: 'Phone', theme: 'frost', pieces: [{ t: 'start', x: 0, y: 0, z: 0, r: 0 }] }));
await sleep(500);
await page.tap('.piece[data-piece="straight"]');
const cell = await page.evaluate(() => { const a = window.__INKTRACK__, ed = a.mode, cam = a.renderer.camera; ed.target.set(0, 0, 10); ed._updateCamera(); const v = new (cam.position.constructor)(0, 0, 10).project(cam); return [((v.x + 1) / 2) * a.renderer.width, ((1 - v.y) / 2) * a.renderer.height]; });
console.log('at', cell, await page.evaluate(([x, y]) => { const e = document.elementFromPoint(x, y); return e.tagName + '.' + e.className; }, cell));
await page.evaluate(() => { window.__EDITOR_DEBUG__ = 1; for (const t of ['pointerdown', 'pointerup', 'pointercancel']) window.addEventListener(t, (e) => console.log(t, e.pointerType, e.pointerId, e.target.tagName,), true); });
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: cell[0], y: cell[1], id: 1 }] });
await sleep(60);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
await sleep(200);
console.log('pieces', await page.evaluate(() => { const ed = window.__INKTRACK__.mode; return [ed.track.pieces.length, JSON.stringify(ed.hoverCell), JSON.stringify(ed.candidate), document.querySelector('.ed-toast').textContent, ed.tool, ed.selected, ed.level, JSON.stringify([...ed.occupancy.keys()])]; }));
console.log(logs.join('\n'));
await browser.close();
