// Recompute each starter track's par time (a clean autopilot lap) and write
// src/tracks/data/par.js. Medal times are derived from par (see progress.js).
// Usage: node scripts/par-times.mjs
import { writeFileSync } from 'node:fs';
import { buildTrack } from '../src/tracks/TrackBuilder.js';
import { STARTER_TRACKS } from '../src/tracks/starterTracks.js';
import { Race } from '../src/race/Race.js';
import { Autopilot } from '../src/race/Autopilot.js';
import { FlightAutopilot } from '../src/race/FlightAutopilot.js';
import { PHYSICS } from '../src/config/physics.js';

const out = {};
for (const track of STARTER_TRACKS) {
  const build = buildTrack(track);
  const race = new Race(build);
  const ap = build.air ? new FlightAutopilot(build.route) : new Autopilot(build.route);
  ap.attach(race.car);
  const c = { throttle: 0, brake: 0, steer: 0, drift: false };
  for (let t = 0; t < 200 && race.state !== 'finished'; t += 1 / PHYSICS.tickRate) {
    race.step(1 / PHYSICS.tickRate, ap.sample(c));
    for (const e of race.drainEvents()) if (e.type === 'respawn') ap.relocate();
  }
  if (race.state !== 'finished') throw new Error(`${track.id}: autopilot did not finish`);
  out[track.id] = Math.round(race.finishTime * 1000) / 1000;
  console.log(track.id.padEnd(16), out[track.id].toFixed(3), 's');
}
writeFileSync(new URL('../src/tracks/data/par.js', import.meta.url), `/** Par times (clean autopilot laps, seconds). Generated by scripts/par-times.mjs. */\nexport default ${JSON.stringify(out, null, 2)};\n`);
