import { launch, sleep } from './pw.mjs';
const url = process.argv[2] || 'http://localhost:4173/';
const { browser, page, logs } = await launch();
await page.goto(url);
await page.waitForFunction(() => window.__INKTRACK__);
await sleep(800);
await page.screenshot({ path: 'screenshots/phase3-idle.png' });
await page.keyboard.down('KeyW');
await sleep(1200);
await page.screenshot({ path: 'screenshots/phase3-speed.png' });
await sleep(1100);
await page.screenshot({ path: 'screenshots/phase3-jump.png' });
await sleep(1500);
await page.keyboard.down('KeyD');
await page.keyboard.down('Space');
await sleep(1000);
await page.screenshot({ path: 'screenshots/phase3-drift.png' });
await page.keyboard.up('Space');
await page.keyboard.up('KeyD');
await sleep(300);
await page.screenshot({ path: 'screenshots/phase3-boost.png' });
const info = await page.evaluate(() => ({ ...window.__INKTRACK__.renderer.info, fps: window.__INKTRACK__.loop.fps }));
console.log(info);
console.log(logs.join('\n'));
await browser.close();
